version: '3.8'

services:
  kafka:
    image: apache/kafka-native:4.1.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: "1"

      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${DOCKER_HOST_IP}:9092

      # Controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@${DOCKER_HOST_IP}:9093"

      # Logs menores
      KAFKA_LOG_RETENTION_BYTES: "10485760"   # 10MB
      KAFKA_LOG_SEGMENT_BYTES: "5242880"     # 5MB
      KAFKA_LOG_RETENTION_MS: "86400000"     # 24h
      KAFKA_LOG_CLEANER_INTERVAL_MS: "10000"
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${DOCKER_HOST_IP}:9092
      KAFKA_CLUSTERS_0_REFRESH_INTERVAL_MS: "10000"
    depends_on:
      - kafka
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  kafka_data:
