version: "3.9"

services:
  kafka:
    image: apache/kafka-native:4.1.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://127.0.0.1:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OPTS: "-Xms192M -Xmx192M"

  agent:
    build:
      context: .
      dockerfile: k8s/Dockerfile.agent
    container_name: agent
    depends_on:
      kafka:
        condition: service_started
    ports:
      - "9091:9090"

  analyser:
    build:
      context: .
      dockerfile: k8s/Dockerfile.analyser
    container_name: analyser
    depends_on:
      kafka:
        condition: service_started
    ports:
      - "9090:9090"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  api:
    build:
      context: .
      dockerfile: k8s/Dockerfile.api
    container_name: api
    depends_on:
      kafka:
        condition: service_started
      analyser:
        condition: service_started
    ports:
      - "9093:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CLUSTERS_0_REFRESH_INTERVAL_MS: "10000"
    profiles:
      - kafka-ui
