---
spring:
  graphql:
    http:
      path: /api/metrics
    websocket:
      enabled: true
      path: /api/metrics
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: analyser.dto.MetricDTO:api.dto.MetricDTO,analyser.dto.ProcessInfoDTO:api.dto.ProcessInfoDTO
        spring.json.use.type.headers: true
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer