---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyser
  template:
    metadata:
      labels:
        app: analyser
    spec:
      containers:
        - env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BOOTSTRAP_SERVERS
                  name: kafka-config
          image: localhost:5000/analyser:local
          imagePullPolicy: Always
          name: analyser
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
      initContainers:
        - command:
            - sh
            - '-c'
            - |
              echo "Waiting for Kafka to be ready..."
              until nc -z kafka 9092; do
                echo "Kafka not ready, sleeping 2s..."
                sleep 2
              done
              echo "Kafka is ready!"
          image: busybox
          name: wait-for-kafka