---
grpc:
  analyser:
    host: agent
    port: 9090
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: analyser
      properties:
        spring.json.trusted.packages: '*'
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer