spring:
  application:
    name: analyser

grpc:
  analyser:
    host: analyser
    port: 8080

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: analyser
      properties:
        spring.json.trusted.packages: '*'
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
