---
grpc:
  analyser:
    host: agent-grpc
    port: 9090
spring:
  application:
    name: analyser
  kafka:
    bootstrap-servers: ${DOCKER_HOST_IP}:9092
    consumer:
      group-id: analyser
      properties:
        spring.json.trusted.packages: '*'
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer